### ISSUE TITLE
Set up Flask Environment

### ISSUE THREAD

**Issue by yt2097** [NYUDevOps2021-recommendation/recommendations#18]
**As a** developer
**I need** a virtual common environment for all team member to use
**So that** we can work remotely and all our code will be compatible and can be merged without issue

**Details & Assumptions:** 

**We will** set up a vagrant file to use a Linux setup using Vagrant and VirtualBox.
**We will** use Python with Flask to develop the project.

**Acceptance Criteria:**

**When I** type "vagrant up" while in the directory of a cloned repository
**I should** have access to a full virtual environment where i can use Flask.

**Comment by AmazingTai** [comment]
Should we use `python venv` in our virtual environment?
