### ISSUE TITLE
Need Swagger API documentation

### ISSUE THREAD

**Issue by AmazingJinwei** [NYUDevOps2021-recommendation/recommendations#2]
**As a**  User 
**I need** the API documented in Swagger 
**So that** I can easily understand how to use the API  

**Details & Assumptions:**
· We can leverage the Swagger support for Python
· We can annotate the code to support Swagger documentation generation
· The documentation endpoint is on the /api-docs URL

**Acceptance Criteria:**
Given completed /api-docs URL
When I follow the instructions on the /api-docs URL
Then it should return the documentation JSON in Swagger format

**Comment by yt2097** [comment]
Hi Jinwei, maybe next time, you can highlight things like ``/api-docs``

**Comment by legendary2018** [comment]
Is the label "technical debt" appropriate for this issue?

**Comment by JinweiDai** [comment]
You mean add "technical debt" ? Or replace the "document" one?
