### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by yt2097** [NYUDevOps2021-recommendation/recommendations#21]
Use Docker inside of your Vagrant VM for any 3rd part services you want to use. e.g., if you use a Redis, MongoDB, PostgreSQL, MySQL database, etc. it should be installed using Docker.

**As a**  developer
**I need** to use Docker inside of Vagrant VM for the database and it should be installed using Docker.
**So that** every developer will have the same database environment

**Details & Assumptions:** 
* Add database environment into vagrantfile

**Acceptance Criteria:**

```gherkin
When issue vagrant up 
Then I should have the complete dev environment include database
```

**Comment by AmazingTai** [comment]
This is fine:)
