### ISSUE TITLE
Add the ability to browse all upsells

### ISSUE THREAD

**Issue by yt2097** [NYUDevOps2021-recommendation/recommendations#6]
**As a** User
**I need** the ability to see all upsells related to the current product
**So that** I can find the best deal

**Details & Assumptions:** 

* The name of the product and the upsell relation should be pass in by the user
* A call to ``GET /recommendation/{product_id}/{upsells}`` should list all upsells

**Acceptance Criteria:**

When I call ``GET /recommendation/{product_id}/{upsells}``
I should see a list of upsells as a JSON string

**Comment by amateurPotato** [comment]
Can we update this, [Issue #5](https://github.com/NYUDevOps2021-recommendation/recommendations/issues/5) and  [Issue #3](https://github.com/NYUDevOps2021-recommendation/recommendations/issues/3) as query recommendation?
